# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gradient for OT (Internal C function)
#'
#' @param Mat the cost matrix
#' @param psi the vector of potentials
#' @export
Grad <- function(Mat, psi) {
    .Call('_WassersteinGoF_Grad', PACKAGE = 'WassersteinGoF', Mat, psi)
}

#' Objective for OT (Internal C function)
#'
#' @param Mat the cost matrix
#' @param psi the vector of potentials
#' @export
Objective <- function(Mat, psi) {
    .Call('_WassersteinGoF_Objective', PACKAGE = 'WassersteinGoF', Mat, psi)
}

#' SGD Algorithm for OT (Internal C function)
#'
#' @param C the descent constant
#' @param Mat the cost matrix
#' @export
SGD_OT <- function(C, Mat) {
    .Call('_WassersteinGoF_SGD_OT', PACKAGE = 'WassersteinGoF', C, Mat)
}

#'  Algorithm for plotting results of OT (Internal C function)
#'
#' @param Mat the cost matrix
#' @param psi the vector of potentials
#' @export
Plot <- function(Mat, psi) {
    .Call('_WassersteinGoF_Plot', PACKAGE = 'WassersteinGoF', Mat, psi)
}

rGausResid <- function(n, dim) {
    .Call('_WassersteinGoF_rGausResid', PACKAGE = 'WassersteinGoF', n, dim)
}

